# Site settings
title: CS6868 Spring 2026
subtitle: Concurrent Programming
baseurl: "/cs6868_s26" # the subpath of your site, e.g. /blog/
url: "http://kayceesrk.github.io" # the base hostname & protocol for your site
syllabus: "http://www.cse.iitm.ac.in/course_details.php?arg=MTk="
githubdir: "kayceesrk/cs6868_s26"

# Author/user information
email: kcsrk@iitm.ac.in
twitter_username: kc_srk
github_username:  kayceesrk
authorurl: "http://kcsrk.info"
address: |
    Department of Computer Science and Engineering
    SSB 413, Indian Institute of Technology, Madras
    Chennai, India 600036

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"
